spring:
  application:
    name: event-recommendation-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: f121d
    url: jdbc:postgresql://localhost:5432/Events
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 1lfd234269kadv43mvn856xl45f7kad423423fkad
  lifetime: 60000

server:
  port: 8083
  url: "http://localhost:${server.port}"