spring:
  application:
    name: event-recommendation-service
  config:
    import:
      - db-config.yml
      - jwt-config.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: find-user-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083
  url: "http://localhost:${server.port}"

kafka:
  topics:
    find:
      by:
        username:
          common:
            request: "FindByUsernameCommonUserReq"
            response: "FindByUsernameCommonUserResp"
          organizer:
            request: "FindByUsernameOrganizerReq"
            response: "FindByUsernameOrganizerResp"