springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /AuthSpecification.yaml
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

  server:
    address: http://localhost:8080