spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: f121d
    url: jdbc:postgresql://localhost:5432/Events
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  signin:
    request: "SignInReq"
    response: "SignInResp"
  register:
    common:
      request: "RegisterCommonUserReq"
      response: "RegisterCommonUserResp"
    organizer:
      request: "RegisterOrganizerReq"
      response: "RegisterOrganizerResp"
    admin:
      request: "RegisterAdminReq"
      response: "RegisterAdminResp"

server:
  port: 8084
  url: "http://localhost:${server.port}"

