spring:
  config:
    import:
      - db-config.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-auth-consumer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "event.rec.service.requests,event.rec.service.responses"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    signin:
      request: "SignInReq"
    register:
      common:
        request: "RegisterCommonUserReq"
      organizer:
        request: "RegisterOrganizerReq"
      admin:
        request: "RegisterAdminReq"
    find:
      by:
        id:
          common:
            request: "FindByIdCommonUserReq"
          organizer:
            request: "FindByIdOrganizerReq"
          admin:
            request: "FindByIdAdminReq"

server:
  port: 8084
  url: "http://localhost:${server.port}"

